### ISSUE TITLE
인코딩 에러

### ISSUE THREAD

**Issue by aask1357** [MerHS/biryo#1]
윈도우 커맨드에서 아래 코드 입력하면 에러가 납니다.
`java -Dfile.encoding=UTF-8 -jar biryo.jar namuwiki.json`

`오류: 기본 클래스 .encoding=UTF-8을(를) 찾거나 로드할 수 없습니다.`

그래서 아래 코드를 뺴고 입력하니깐
`-Dfile.encoding=UTF-8 `
텍스트 파일이 만들어지긴하는데 제목이 깨져서 나옵니다.

**Comment by MerHS** [comment]
-Dfile.encoding=UTF8 로 바꿔서 한번 해보시기 바랍니다. 
그래도 일주일 후에 새로운 버전을 올릴텐데 그 때 다시 시도해주세요.

**Comment by MerHS** [comment]
PowerShell등 일부 환경에서 -Dfile.encoding을 잘못 읽는 경우가 있습니다 (https://stackoverflow.com/questions/33393001/specify-the-default-file-encoding-in-java)

`java "-Dfile.encoding=UTF8" -jar biryo.jar namuwiki.json` 같이 써주면 됩니다.
