### ISSUE TITLE
나무위키 2103년도 덤프에서 파일이 제작되지 않습니다.

### ISSUE THREAD

**Issue by LiveTrack-X** [MerHS/biryo#11]

**Comment by MerHS** [comment]
json 덤프의 namespace 필드가 string에서 number로 바뀐것이 원인인 것 같습니다.

1차적으로 수정해서 1.3.1을 올리겠으나, 그동안 나무위키 문법 업데이트가 있었기 때문에 그것들을 반영해서 1.4 버전을 만들겠습니다.
