### ISSUE TITLE
틀링크가 작동하지 않습니다

### ISSUE THREAD

**Issue by nizut** [MerHS/biryo#4]
<img src="https://i.imgur.com/qaqVa1G.jpg" title="Screenshot_20180612-141301.jpg"/>
<img src="https://i.imgur.com/v8CxSAi.jpg" title="Screenshot_20180612-141252.jpg"/>
이 사진처럼 틀에서 다른 문서로 넘어가려하면 에러가 납니다.

**Comment by MerHS** [comment]
무슨 링크를 눌러서 저 화면이 떴는지 알려주실 수 있나요?
현재 제가 있는곳 환경상 확인이 힘듭니다.

**Comment by nizut** [comment]
위에 뷔슈 드 노엘이 열린 페이지의 틀에서 어느 디저트를 누르던 저런 에라가 발생합니다.

**Comment by raonious** [comment]
<img src="https://i.imgur.com/UftulkV.gif" title="videotogif_2018.06.21_19.56.33.gif"/>

**Comment by nizut** [comment]
https://gfycat.com/KlutzyCreepyCoyote

**Comment by MerHS** [comment]
현재 제가 가진 안드로이드 mdict 앱과 윈도우 mdict 앱으로는 재현이 되지 않는데 혹시 사진의 앱이 무슨 앱인지 알려주실 수 있나요?
그리고 `틀:유로피안 디저트` 항목에 가보면 틀 하나와 밑에 [source] 링크가 있을텐데 [source]링크를 눌러서 나오는 html 태그를 복사해서 붙여주시면 디버깅에 더 도움이 됩니다.

**Comment by nizut** [comment]
사진ㅇ 앱은 bluedict입니다.
html태그가
source://%ED%8B%80:%EC%9C%A0%EB%A1%9C%ED%94%BC%EC%95%88 %EB%94%94%EC%A0%80%ED%8A%B8
이것인가요?

**Comment by MerHS** [comment]
해당 앱에서는 소스링크가 작동하지 않나보네요. 
다다음주에 나가서 확인해보도록 하겠습니다.

**Comment by nizut** [comment]
감사합니다

**Comment by MerHS** [comment]
해당 앱(bluedict)의 버그같습니다. 
[MDict](https://play.google.com/store/apps/details?id=cn.mdict&hl=en) 공식 앱 등의 대안이 있으니 해결을 원하시면 사용해주시기 바랍니다.
